### ISSUE TITLE
Add database contents to repository

### ISSUE THREAD

**Issue by luke-segars** [hybrasyl/server#1]
Hello! I'm working on getting the Hybrasyl server code to build and trying to produce some instructions that would be useful to others. The problem is that I can't test it because there's no data to populate the MySQL database with. Would you guys mind publishing a dump of the most complete version of the database, even if it's not 100% there yet?

Would build instructions be of interest or do those already exist somewhere that I missed?

**Comment by luke-segars** [comment]
Thanks for 45ec726, @baughj! I'm now seeing the schema over in Ealagad; sorry I missed that before. I'm still not able to find any default *content* of the databases (default warp locations, nations, etc) to match standard DA. It seems like a lot of that exists in the production and staging servers; is that something that could be easily shared as well, even if incomplete? 

An SQL dump would be a relatively easy way for others to chip in while you guys build support for yaml...thoughts?

**Comment by baughj** [comment]
Hi Luke,

Unfortunately as discussed on the hybrasyl users list, we are currently of the opinion that distributing this data via Github is not possible as we do not own the copyrights to it. 

@Fluffguck can tell you what we are looking for in terms of missing content, though, realistically, the main goal of the project at this point is completing the server functionality as without it the content is somewhat meaningless.

It's my intent that part of the "developer's guide" for setting up the server should include instructions on making a map & test items (e.g. "Stick") to get someone started working with Hybrasyl. We could also provide a seed SQL file that simply adds a few test maps / items / worldmap / blah to the database.

**Comment by luke-segars** [comment]
Good point Justin. Adding a section describing how to populate the DB with
enough info to log on and walk around somewhere would be great. It might be
worth adding some more detail about the schema in the guide as well if
that's going to be a common developer task (and it sounds like it might be).

Is "Mileth + stick" something you could help me with? I'm also happy to
bang on it but I'm not currently familiar with how to identify maps to the
client.

**Comment by baughj** [comment]
21ec0c3b77d08827cb94bcb8489770c12a37fd4d is in master and I believe resolves the getting started task.

For reference, `lodXXXX.map` on the client side is the ID of the map in Hybrasyl, as well, as it's what the client expects. So `lod500.map` = map ID 500 on the server.

**Comment by luke-segars** [comment]
This is awesome Justin, thanks! I was able to log in tonight for the first time :)

Note that you also need to define a nation called Mileth since that's currently hard-coded as the default, and it's also helpful to create a "gamemaster" flag. The latter is probably a good one to add to the developer's guide, though the former might be nice to introduce into seed.sql if the risks you mentioned aren't an issue. If so then it might not hurt to generalize the constant that is currently called "Mileth."

I think we can consider this one closed. Very exciting, thanks again.
