### ISSUE TITLE
[Issue] User Logon generates KeyNotFoundException error

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#113]
Note: This occurred on a local server.

Custom XML was created "Dirk" using a modified version of the "stick" xml. Originally only the "Sprite" number was altered. I noticed that the graphic did change in the inventory and character screen, but not the equiped item in the general world view. I changed the DisplaySprite value to 2, and reloaded the Server. When I attempted to login as that character again, the error was generated.

==================

> ###System.Collections.Generic.KeyNotFoundException occurred
>   HResult=0x80131577
>   Message=The given key was not present in the dictionary.
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
>    at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    at Hybrasyl.WorldDataStore.Get[T](Object key) in C:\Users\Agrus\Desktop\Darkages-Workspace\Server\server\hybrasyl\WorldDataStore.cs:line 63
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    at Hybrasyl.InventoryConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\Users\Agrus\Desktop\Darkages-Workspace\Server\server\hybrasyl\Inventory.cs:line 384
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

====================
[AgrusJsonRedisData.txt](https://github.com/hybrasyl/server/files/1537955/AgrusJsonRedisData.txt)

**Comment by blueowlstudio** [comment]
As per discussion with Kedian:

>> "Inventory":[null,{"Name":"Dirk","Count": 1,"Id": 1495974122}
> i can't remember off the top of my head how we generate the ID, but it may in fact be tied to the display sprite

**Comment by norrismiv** [comment]
Items are referenced by hash id. By altering the xml, the hash id has changed, and the key not found exception occurred

**Comment by baughj** [comment]
This is not desirable behavior; changing `DisplaySprite` or indeed `Sprite` on an item should not render a player unable to login.

**Comment by norrismiv** [comment]
This was your design as you essentially said previously this data should never change

**Comment by baughj** [comment]
`/shrug`

```
 return 31 * Name.GetHashCode() * ((Properties.Restrictions?.Gender.GetHashCode() ?? Gender.Neutral.GetHashCode()) + 1) *
                               Properties.Appearance.DisplaySprite.GetHashCode();
```
...most likely just `Name.GetHashCode` and `Gender` are sufficient here

**Comment by baughj** [comment]
This is fixed.
