### ISSUE TITLE
[Issue] Repeating Casting Sounds when Character has Status Active on them.

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#127]
Casting the spell Armachd, causes the casting sound to be repeated until the spell duration expires. 

[ArmachdStatus.txt](https://github.com/hybrasyl/server/files/1623983/ArmachdStatus.txt)
[ArmachdCastable.txt](https://github.com/hybrasyl/server/files/1623985/ArmachdCastable.txt)

Based on a brief look, CreatureStatus.ProcessEffects() [Line 287] is cast CreatureStatus.OnTick(), and contains CreatureStatus.ProcessSfx(). Within ProcessSfx() there does not appear to be any advanced logic on whether to play the sound associated with the spell.

**Comment by baughj** [comment]
Should be fixed by #147 .
