### ISSUE TITLE
Scripting

### ISSUE THREAD

**Issue by norrismiv** [hybrasyl/server#131]
![d217be69-ba2f-404d-9f4a-682b7fa7fa3a](https://user-images.githubusercontent.com/16417541/34910381-c907cf24-f881-11e7-8fc5-6dcbbdf466d0.png)
![cbc475f5-4d08-489f-b505-50f99ca1f794](https://user-images.githubusercontent.com/16417541/34910382-c9118b72-f881-11e7-9c7e-8c93478174f9.png)

**Comment by baughj** [comment]
never let it be said you aren’t a professional

**Comment by norrismiv** [comment]
You asked for a github issue. That shows it. Much more discussion needs to
be had around this before a formal issue can be created, which is what
happens in any professional environment.

But, I did oblige and create the issue without any discussion, as asked.
