### ISSUE TITLE
Small question for XML

### ISSUE THREAD

**Issue by shadowoffice** [hybrasyl/server#133]
![image](https://user-images.githubusercontent.com/2808349/35146844-53764968-fcda-11e7-854a-be02b7823d45.png)
have this error whit my code on my database on my git and have not idea what is this error XD
* [HydraDB](https://github.com/shadowoffice/HybraDB/)

**Comment by baughj** [comment]
The map error says what the error is (in French). Or do you mean the status error?

**Comment by shadowoffice** [comment]
Translate in english for you 👍 

the start tag 'warps' on line 4 does not match the end tag warps line 14 position 4

the key was missing from the dictionary

**Comment by baughj** [comment]
Your XML is malformed. The error says exactly where it is: https://github.com/shadowoffice/HybraDB/blob/098c2dda84322be96b1e8aa0af18b2ebc4154560/maps/Mileth/Mileth%20Inn%20Corridor%201.xml#L14 - there is two `</Warp>` closing tags, which is invalid.

**Comment by shadowoffice** [comment]
Thx for respond 👍

**Comment by baughj** [comment]
Let me know if you need anything else, closing.
