### ISSUE TITLE
[Issue] Creature unable to attack, generates error

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#134]
When the Monster._variance is negative, Monster._simpleDamage is unable to Convert the formula to a UInt32, since the value would be negative. 

When _simpleDamage is called by Monster.SimpleAttack, the system produces the error.

![image](https://user-images.githubusercontent.com/33741983/35188312-d2f81cb2-fde7-11e7-9d30-74b0372a375f.png)

**Comment by baughj** [comment]
Resolved in 0.7.0
