### ISSUE TITLE
[Issue] User List Shows Users Who Have Logged Off

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#138]
User list still shows users who have logged off.

Note: In the screen shot only the user "Agrus" is current logged into the server. "Test" was logged in, but exited.

![image](https://user-images.githubusercontent.com/33741983/35286621-5f542528-0015-11e8-9577-68c4a0f098ba.png)

**Comment by baughj** [comment]
https://github.com/hybrasyl/server/pull/141 fixes this.
