### ISSUE TITLE
Fody 1.25.0 has trouble building; consider upgrading?

### ISSUE THREAD

**Issue by anyweez** [hybrasyl/server#14]
This might be my fault from playing around with things I don't understand but I've been getting the following exception thrown from Fody when I build Hybrasyl server:

    1>MSBUILD : error : Fody: An unhandled exception occurred:
    1>MSBUILD : error : Exception:
    1>MSBUILD : error : Unknown custom metadata item kind: 6
    1>MSBUILD : error : StackTrace:
    1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
    1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
    1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
    1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
    1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
    1>MSBUILD : error :    at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
    1>MSBUILD : error :    at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
    1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
    1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
    1>MSBUILD : error :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
    1>MSBUILD : error :    at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
    1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
    1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
    1>MSBUILD : error :    at InnerWeaver.ReadModule() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\ModuleReader.cs:line 23
    1>MSBUILD : error :    at InnerWeaver.Execute() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\InnerWeaver.cs:line 28
    1>MSBUILD : error : Source:
    1>MSBUILD : error : Mono.Cecil.Pdb
    1>MSBUILD : error : TargetSite:
    1>MSBUILD : error : Void ReadCustomMetadata(Microsoft.Cci.Pdb.BitAccess)

The latest version out is 1.28.3, and when I update the issue goes away. I first encountered this error while trying to build on Linux (hence the Mono references), though I'm getting this error on Windows now.

Would it be OK to upgrade to the latest version? Alternatively I can dig into what's going on here more but my understanding of Fody, etc is approximately zero so that will prob take a bit.

**Comment by baughj** [comment]
Upgraded a while ago, so this ticket is now irrelevant. Thank you for reporting it though!
