### ISSUE TITLE
[Issue] Server Start Error

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#140]
Getting an error when attempting to start up the server.

Have deleted the config file, and generated a new one. Redis database also flushed.

![image](https://user-images.githubusercontent.com/33741983/35421650-3ebc43c8-01f9-11e8-8e2d-9698bc619467.png)

**Comment by moseleyc** [comment]
Config file attached:

[config.txt](https://github.com/hybrasyl/server/files/1666335/config.txt)

**Comment by baughj** [comment]
Fix is in develop, and tested.
