### ISSUE TITLE
[Issue] Status Duration Calculation Issue

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#144]
Separate, but partly related issue: If the Castable doesn't set a Duration for the Status, then the default is 0. Same with Statuses Duration. But _durationOverride (CreatureStatus-Line:164) is calculated by multiplying these two values...if either of these is left to the default then the value would always be 0....

What is the purpose behind multiplying these values? Or should this be an addition operator?

**Comment by baughj** [comment]
Fixing in your active branch; this is a combination of wrong intent XML-wise and my own error.
