### ISSUE TITLE
[XML/Castables] Further iteration on Equipment Restrictions

### ISSUE THREAD

**Issue by Caeldeth** [hybrasyl/server#152]
In addition to restricting castables to grouped equipment and weapons, Restrictions should be able to call a specific item being equipped.  Suggest new element with attribute:
<Equipped Slot=" ">Item Name</Equipped>

This would support functionality for leasaich spells to not involve a popup, quality of life improvement.  Could be useful for other things as well.

**Comment by Mannyita** [comment]
Can you please remove me from all threads for hybrasyl I have tried doing it my self and I end up with 50+ emails in my inbox.

**Comment by norrismiv** [comment]
@Mannyita this is on you to do. We do not control your github account.

**Comment by Caeldeth** [comment]
Closed, issue refactored.
