### ISSUE TITLE
[Creatures] Property Case Incorrect

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#153]
![image](https://user-images.githubusercontent.com/33741983/36077316-325d9ce4-0f1e-11e8-852a-f0f9ed449313.png)

**Comment by moseleyc** [comment]
![image](https://user-images.githubusercontent.com/33741983/36077765-a735aade-0f23-11e8-8d32-e8baacf36b88.png)

**Comment by norrismiv** [comment]
The casing here is correct. Elements are pascal case while attributes are camel case. Attributes that are not camel case should be corrected.

**Comment by moseleyc** [comment]
Alright. Basically every attribute in Creature will need to be adjusted, then. Think that's the same with the other XSD's as well...might be easier to make them all pascal case....

![image](https://user-images.githubusercontent.com/33741983/36079046-aff39d56-0f33-11e8-8491-3d27dae01b2d.png)

![image](https://user-images.githubusercontent.com/33741983/36079053-bfdec218-0f33-11e8-995f-ee2e9086c1b3.png)

===================
IE: From Castables

![image](https://user-images.githubusercontent.com/33741983/36079076-176a30c6-0f34-11e8-9501-f4444a7340f8.png)

![image](https://user-images.githubusercontent.com/33741983/36079091-27e5ec38-0f34-11e8-8d25-6b89a51d983c.png)

IE: From 

![image](https://user-images.githubusercontent.com/33741983/36079097-363fa620-0f34-11e8-823c-5c19338801b0.png)

**Comment by baughj** [comment]
I am OK with pascal case (e.g. SpellGroup vs spellGroup) for everything. I don't really care what we use so long as it is standard. I don't see a need to have mixed case types between elements / attributes.

**Comment by baughj** [comment]
will be fixed in 0.7.0
