### ISSUE TITLE
Monster AI causes terrible lag under load

### ISSUE THREAD

**Issue by baughj** [hybrasyl/server#162]
Currently, with 100s of mobs on the screen, there is a hellacious amount of server lag. Investigate whether the AI thread is blocking something else, or whether the queue consumer itself is being flooded with move / etc packets.

**Comment by moseleyc** [comment]
@100 Bees. Didn't have trouble with laggy messages, but moving was definitely problematic

Screen shot of the server cmd window:
![image](https://user-images.githubusercontent.com/33741983/50674176-92920700-0f98-11e9-8456-f0bbcaabdf73.png)

Info messages (as seen in the screen shot) were basically going non-stop

![image](https://user-images.githubusercontent.com/33741983/50674214-eac90900-0f98-11e9-9460-c749d224086a.png)

**Comment by norrismiv** [comment]
yeah this is the lag i was talking about. this has to do with how we're queuing and dequeuing the packets. seems like some of this needs to be broken out into its own threads.
