### ISSUE TITLE
[XML/Castables] Implement $RAND for Formula Parser

### ISSUE THREAD

**Issue by Caeldeth** [hybrasyl/server#185]
Per discussion, implement simple random number generator variable for formula parser:

$RAND_10
$RAND_100
$RAND_1000

**Comment by norrismiv** [comment]
could this not just be `$RAND_MIN_MAX`?

**Comment by Caeldeth** [comment]
Yes

**Comment by norrismiv** [comment]
i see

**Comment by baughj** [comment]
🍔

**Comment by norrismiv** [comment]
🥇 ⭐ 🌟 🏅

**Comment by baughj** [comment]
Added in 0222236
