### ISSUE TITLE
Xmlserializer Deserialize Issue

### ISSUE THREAD

**Issue by Jinori** [hybrasyl/server#188]
Some items in DarkAges have  #base/combat stat modifiers under -127 or over 127 (the maximum for SByte) being used to deserialize.

For example, the current hit mod for "peasant scythe" in the community-maintained database contains a modifier of 255, which is the maximum for byte.

Granted.. these items are freaks of nature and rarely used.. But they exist.

**Comment by norrismiv** [comment]
I just investigated this, and there's currently no item in the game that is individually +127 hit or -127 hit. The client itself responds with an `sbyte` value, and looking at both `da-wizard.com` and `vorlof.com`, `Scythe` has not hit modifier on it. 

The maximum hit value I've found on any item in the game currently is +40, and that exists on `Blackstar Whip`.

Are you referring to a total possible hit value at a character/creature level? If so, we use a `long` value for that at the server level.

**Comment by baughj** [comment]
I think @Jinori is talking about some specific examples in shadowoffice/hybradb. 

For instance: https://github.com/shadowoffice/HybraDB/blob/master/xml/items/peasant_scythe.xml has a value of 256 for hit, which is obviously wrong, whether byte or sbyte.

**Comment by baughj** [comment]
Fixed in https://github.com/shadowoffice/HybraDB/pull/2

**Comment by baughj** [comment]
@Jinori let me know if this addresses your issue, or if you believe there is a more specific problem with XSD typing

**Comment by Jinori** [comment]
That should be it then. I was under the impression those were the actual value of that item.
In my Anvil program, I'll just set min and max to stay within sbyte when creating items.

Thanks!
