### ISSUE TITLE
[Server] Spell Line Reduction NYI

### ISSUE THREAD

**Issue by Caeldeth** [hybrasyl/server#211]
Spell line reduction exists in XML but is not implemented on server.  Existing scenarios to account for:

1) (Diana) x+/-y (e.g., 1 line becomes 0 with -1, or 2 with +1)
2) (Gaea) >= x becomes x (e.g., everything over 3 lines becomes 3 lines)
3) (Apollo)  all becomes x (e.g., everything becomes 3 lines)
4) (Zeus/Kronos) x becomes y (e.g., all 4 line becomes 2 line)
5) (Ares/Hermes) specific spell group becomes x (all cradh/ioc becomes 0 line)

Open for debate scenarios:
1) Cost reduction
2) Cooldown reduction
3) Existing scenario is restricted to 2h Staff items only (hardcoded per m2/steve).  Propose being general weapon property

**Comment by Caeldeth** [comment]
Hermes/Ares could be accounted for in XML via categories.  IF Cat1="Spell" AND Cat2="Ioc" THEN SpellLines=0

**Comment by moseleyc** [comment]
Just a note that I'm working away on this. Just in case someone else might be as well.

**Comment by Caeldeth** [comment]
This is actually fixed locally, has not been pushed to master yet!
