### ISSUE TITLE
Map XML Loading

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#238]
When different Map XML files reference the same Id, all of the map XMLs except the first one will not get SetWithIndex (World.cs => Line 339: if (!WorldData.SetWithIndex(map.Id, map, map.Name)) )

![image](https://user-images.githubusercontent.com/33741983/90971184-26904980-e4c2-11ea-9a68-41fa5a48d73c.png)

![image](https://user-images.githubusercontent.com/33741983/90971177-0cef0200-e4c2-11ea-87e9-63552ff0fae3.png)

**Comment by Jinori** [comment]
Looks like you're loading in two differently named rooms. Should they even have the same ID?

**Comment by norrismiv** [comment]
Map IDs are unique. You cannot use the same Map ID for multiple maps.

**Comment by Caeldeth** [comment]
Looks like the community database of examples could use a little love - stay tuned, this is added to my list!

**Comment by moseleyc** [comment]
@Caeldeth came across a few issues so far. I can just fork the repo, and make a PR for the changes I've had to make.
@norrismiv Thought that might be the case but wasn't sure. Thanks for confirming.
