### ISSUE TITLE
Equipment bug.

### ISSUE THREAD

**Issue by woghks123** [hybrasyl/server#42]
What is, after equip my equipment and reconnect, that equipment's status's becomes base status

For examples, my ACs are 100, when i reconnect after equipment improves +3 ac, my base AC changed 103

**Comment by baughj** [comment]
Verified, this is a result of us not recalculating item bonuses on login.

**Comment by baughj** [comment]
This issue should now be resolved. Please let us know if you see it again.

**Comment by woghks123** [comment]
thanks,suffer many hardships Justin.
