### ISSUE TITLE
[Request] - Track previous class in scripting

### ISSUE THREAD

**Issue by Caeldeth** [hybrasyl/server#51]
In old dark ages, customization of skills/spells for subpaths was not possible because previous class was not able to be detected by scripts.  Scripts were able to determine pure vs. not pure.  More customization would be allowable if the ability to detect the previous class were enabled.

Rough example (how it currently is):
If Pure Wizard 
   then give Wings of Protection, Fas Spiorad
   else give Fas Spiorad

Proposed:
If Pure Wizard then give Wings of Protection, Fas Spiorad
  elseif Priest/Wizard, give spell 1
  elseif Rouge/Wizard, give spell 2
  elseif Warrior/Wizard, delete.char
  elseif Monk/Wizard, give spell 3
end

**Comment by baughj** [comment]
OK - this is a simple data change and easy to implement, and a useful one.

**Comment by bigspoondude** [comment]
Poor Wiz-Warr.

**Comment by baughj** [comment]
Added in 0222236
