### ISSUE TITLE
[Feature Request] nadur debuff

### ISSUE THREAD

**Issue by bigspoondude** [hybrasyl/server#54]
Please allow a temporary debuff to override an Aislings current defensive element. Also allow Wizards to cast nadur on Aisling. Wizards will be able to override the debuff and effectively revert the debuff.

In a PvP setting this will add a new dynamic for bringing Wizards or Wizard subs to change element or counter element.

Example: creag nadur 15 seconds 
This benefits a team of Karura Druids with a Wiest caster.

**Comment by Caeldeth** [comment]
Tagging this for testing in a few releases.

**Comment by Caeldeth** [comment]
Implemented.
