### ISSUE TITLE
[Request] Address monster naming oddities and inconsistancies

### ISSUE THREAD

**Issue by bigspoondude** [hybrasyl/server#57]
Dave had a few odd instances where he named creatures a certain way. A prime example is the Unseelie Wisp and Satyr. The Unseelie prefix denotes the creature is a member of the Unseelie Court of the Fae (Winter Court, Evil Court, etc). Dark Ages does not have Fae Courts and that being the case, how is it possible to have members of a court that does not exist?

Another issue is the Dhole Larva. A dhole is a member of the canine family, and does not possess a larval state. It is possible that it is using an archaic spelling where an h follows a d, which in modern times would be dole larva or a ringworm.

My request would be to update names as needed or in the case of the Unseelie, to implement the Fae Courts. There is a wealth of lore surrounding the Fae and this would be an awesome opportunity to enrich the gaming experience.

**Comment by FallenDev** [comment]
Unseelie Satyr is from CR isn't it?

**Comment by bigspoondude** [comment]
Yes it is.

**Comment by Caeldeth** [comment]
This is actually correct behavior.  There is indeed a Seelie Court, referenced in an unreleased map that is a copy of the Singing Sylvan Glade.  Won't fix!
